using StockSimulationMVC.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.ModelConfiguration;
using System.Linq;
using System.Web;

namespace StockSimulationMVC.ObjectContext
{
    public class MonthRevenueMapping : EntityTypeConfiguration<MonthRevenueModel>
    {
        public MonthRevenueMapping()
        {
            ToTable("MonthRevenue");
            Property(m => m.ID);
            Property(m => m.Company);
            Property(m => m.CompanyName);
            Property(m => m.Date);
            Property(m => m.AnnouncementDate_SALE);
            Property(m => m.Sale_Monthly);
            Property(m => m.Sale_MonthlyLastYear);
            Property(m => m.YoYPercentage_MonthlySale);
            Property(m => m.MoMPercentage_MonthlySale);
            Property(m => m.MonthsofMoMPercentage_MonthlySale);
            Property(m => m.Sale_Accumulated);
            Property(m => m.Sale_AccuLY);
            Property(m => m.YoYPercentage_AccSales);
            Property(m => m.HighestMonthlySales);
            Property(m => m.HighestMonthlySalesYM);
            Property(m => m._MonthSalesHMonthSales_1_Percentage);
            Property(m => m.LowestMonthlySales);
            Property(m => m.LowestMonthlySalesYM);
            Property(m => m._MonthSalesLMonthSales_1_Percentage);
            //Property(m => m.HighestLowest_AllTime_);
            //Property(m => m.HighestLowest_Last12M_);
            //Property(m => m.HighestLowest_Month_);
            //Property(m => m.Sale_AccuLast12M);
            //Property(m => m.Sale_AccuLY12M);
            //Property(m => m.YoYPercentage_AccSalesL12M);
            //Property(m => m.Sale_AccuLast3M);
            //Property(m => m.Sale_AccuLY3M);
            //Property(m => m.YoYPercentage_AccSalesL3M);
            //Property(m => m.MoMPercentage_AccSalesL3M);
            //Property(m => m.QoQPercentage_AccSalesL3M);
            //Property(m => m.AnnouncementDate_Earning);
            //Property(m => m.Pre_taxIncome_Month);
            //Property(m => m.Pre_taxIncome_MonthLY);
            //Property(m => m.YoYPercentage_MonthPre_taxIncome);
            //Property(m => m.Pre_taxIncomeAccumulated);
            //Property(m => m.Pre_taxIncomeAccu_LY);
            //Property(m => m.YoYPercentage_AccPre_taxIncome);
            //Property(m => m.NetIncome_Month);
            //Property(m => m.NetInc_MonthLY);
            //Property(m => m.YoYPercentage_MonthNetInc);
            //Property(m => m.NetIncAccumulated);
            //Property(m => m.NetIncAccu_LY);
            //Property(m => m.YoYPercentage_AccNetInc);
            //Property(m => m.ForcastedSale);
            //Property(m => m.ForcastedSaleDate);
            //Property(m => m.SaleToTargetPercentage);
            //Property(m => m.ForecastedPre_taxIncome);
            //Property(m => m.ForecastedNetInc);
            //Property(m => m.ForcastEraningDate);
            //Property(m => m.Pre_taxIncomeToTargetPercentage);
            //Property(m => m.NetIncToTargetPercentage);
            //Property(m => m.EarningSale_Month);
            //Property(m => m.EarningSale_Accu);
            //Property(m => m.NetIncSale_Month);
            //Property(m => m.NetIncSale_Accu);
            //Property(m => m.NetWorth);
            //Property(m => m.ContingentLiability_ParentCompany);
            //Property(m => m.ContingentLib_ParentCo_NetWorth);
            //Property(m => m.LoanToOther_ParentCompany);
            //Property(m => m.Loan_ParentCo_NetWorth);
            //Property(m => m.OutstandingShares);
            //Property(m => m.SalePerMonth);
            //Property(m => m.SaleShare_Accu);
            //Property(m => m.SaleShare_AccuL12M);
            //Property(m => m.SaleShare_AccuL3M);
            //Property(m => m.EPS_BefTax_Month);
            //Property(m => m.EPS_BefTax__Accu);
            //Property(m => m.EPS_BefT__PerM__W_);
            //Property(m => m.EPS_BefT__Accu__W_);
            //Property(m => m.EPS_AftT__PerMonth);
            //Property(m => m.EPS_AftTax__Accu);
            //Property(m => m.EPS_AftT__PerM__W_);
            //Property(m => m.EPS_AftT__Accu__W_);
            //Property(m => m.BPS);
            //Property(m => m.OverdueRatePercentage);
            //Property(m => m.ObservedLoan_Percentage_);
            //Property(m => m.TotalNPLPercentage);
            //Property(m => m.OperatingProfit);
            //Property(m => m.OperatingProfit_Month);
            //Property(m => m.OperatingProfitMargin);
            //Property(m => m.OperatingProfitMargin__Month);
            //Property(m => m.ConsolidatedSale_Month);
            //Property(m => m.ConsolidatedSale_MonthLY);
            //Property(m => m.ConsolidatedYoYPercentage_MonthSale);
            //Property(m => m.ConsolidatedMoMPercentage_MonthSale);
            //Property(m => m.MonthsofConsolidatedMoMPercentage_MonthSale);
            //Property(m => m.ConsolidatedSale_Accumulated);
            //Property(m => m.ConsolidatedSale_AccuLY);
            //Property(m => m.ConsolidatedYoYPercentage_AccSales);
            //Property(m => m.ConsolidatedOperatingProfit);
            //Property(m => m.ConsolidatedOperatingProfit_Month);
            //Property(m => m.ConsolidatedOperatingProfitMargin);
            //Property(m => m.ConsolidatedOperatingProfitMargin__Month);
            //Property(m => m.ConsolidatedPre_taxIncome_Month);
            //Property(m => m.ConsNetIncomeAttributabletoOwnersofParent_Month);
            //Property(m => m.ConsolidatedPre_taxIncomeAccumulated);
            //Property(m => m.ConsNetIncomeAttributabletoOwnersofParent_Accumulated);
            //Property(m => m.ConsolidatedHighestLowest_AllTime_);
            //Property(m => m.ConsolidatedSales_YN_);
            //Property(m => m.Cons_FirstSale_Month);
            //Property(m => m.Cons_FirstYoYPercentage_MonthSale);
            //Property(m => m.Cons_FirstMoMPercentage_MonthSale);
            //Property(m => m.Cons_FirstSale_Accumulated);
            //Property(m => m.Cons_FirstYoYPercentage_AccSales);
            //Property(m => m.ConsolidatedIncome_YN_);
            //Property(m => m.Cons_FirstPre_taxIncome_Month);
            //Property(m => m.Cons_FirstNetIncome_Month);
            //Property(m => m.Cons_FirstPre_taxIncomeAccumulated);
            //Property(m => m.Cons_FirstNetIncAccumulated);
        }
    }
}